# Generated by Django 3.1.3 on 2020-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20201125_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='finish_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='progress',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
