# Generated by Django 3.1.3 on 2020-11-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_auto_20201125_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('active', 1), ('inactive', 2), ('finished', 3)], default='inactive', max_length=32),
        ),
    ]
