# Generated by Django 3.1.3 on 2020-11-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_auto_20201125_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('finished', 'Finished')], default='inactive', max_length=32),
        ),
    ]
