# Generated by Django 3.1.3 on 2020-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_auto_20201125_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='command',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
